package GiML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptEnvironment = createDescriptorForEnvironment();
  /*package*/ final ConceptDescriptor myConceptGameInstance = createDescriptorForGameInstance();
  /*package*/ final ConceptDescriptor myConceptTeamInstance = createDescriptorForTeamInstance();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptEnvironment, myConceptGameInstance, myConceptTeamInstance);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Environment:
        return myConceptEnvironment;
      case LanguageConceptSwitch.GameInstance:
        return myConceptGameInstance;
      case LanguageConceptSwitch.TeamInstance:
        return myConceptTeamInstance;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList();
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForEnvironment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GiML", "Environment", 0x8c6624b06c1e43b4L, 0xb7ca7509cedad45bL, 0x34b4aa92216592f1L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:3aec94a4-ce6f-409b-b63c-bd90270fe589(GiML.structure)/3797847930382422769");
    b.version(2);
    b.aggregate("teamInstances", 0x19b939282eb7b512L).target(0x8c6624b06c1e43b4L, 0xb7ca7509cedad45bL, 0x34b4aa92216592f5L).optional(true).ordered(true).multiple(true).origin("1853575566384936210").done();
    b.alias("environment");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGameInstance() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GiML", "GameInstance", 0x8c6624b06c1e43b4L, 0xb7ca7509cedad45bL, 0x19b939282e29bb24L);
    b.class_(false, false, true);
    b.origin("r:3aec94a4-ce6f-409b-b63c-bd90270fe589(GiML.structure)/1853575566375631652");
    b.version(2);
    b.aggregate("environment", 0x19b939282e29bb38L).target(0x8c6624b06c1e43b4L, 0xb7ca7509cedad45bL, 0x34b4aa92216592f1L).optional(false).ordered(true).multiple(false).origin("1853575566375631672").done();
    b.aggregate("gameModel", 0x19b939282e29bb5bL).target(0x1472546da96448a0L, 0xa11e4271b165a42cL, 0x23eac9cba952c550L).optional(false).ordered(true).multiple(false).origin("1853575566375631707").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTeamInstance() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GiML", "TeamInstance", 0x8c6624b06c1e43b4L, 0xb7ca7509cedad45bL, 0x34b4aa92216592f5L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:3aec94a4-ce6f-409b-b63c-bd90270fe589(GiML.structure)/3797847930382422773");
    b.version(2);
    b.aggregate("team", 0x34b4aa92216592f9L).target(0xbc08d5ab032d46dcL, 0x996446504a89c9c8L, 0x3eecc86bd037a735L).optional(false).ordered(true).multiple(false).origin("3797847930382422777").done();
    b.aggregate("players", 0x34b4aa92216592fcL).target(0xbc08d5ab032d46dcL, 0x996446504a89c9c8L, 0x3eecc86bd037a739L).optional(true).ordered(true).multiple(true).origin("3797847930382422780").done();
    b.alias("teamInstance");
    return b.create();
  }
}
