package RetrieveInstitutes.plugin;

/*Generated by MPS */


public class Game {
  public String gameId;
  public String name;
  public String description;

  public Game(String gameId, String name, String description) {
    this.gameId = gameId;
    this.name = name;
    this.description = description;
  }
}
