package GameData.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_periodValues extends EnumerationDescriptorBase {

  public EnumerationDescriptor_periodValues() {
    super(0xdc26d82528834e88L, 0x933cf0e9f65c69c4L, 0x23eac9cba9809de7L, "periodValues", "r:d9f70ad8-7ff2-45f8-b800-65156a39d64d(GameData.structure)/2588102812437093863", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_weekly_0 = new EnumerationDescriptor.MemberDescriptor("weekly", "weekly", "r:d9f70ad8-7ff2-45f8-b800-65156a39d64d(GameData.structure)/2588102812437093864", "weekly");
  private final EnumerationDescriptor.MemberDescriptor VALUE_daily_0 = new EnumerationDescriptor.MemberDescriptor("daily", "daily", "r:d9f70ad8-7ff2-45f8-b800-65156a39d64d(GameData.structure)/2588102812437093884", "daily");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_weekly_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_weekly_0, VALUE_daily_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "weekly":
        return VALUE_weekly_0;
      case "daily":
        return VALUE_daily_0;
    }
    return null;
  }
}
