package GameData.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BonusPointType = 0;
  public static final int ChallengeData = 1;
  public static final int GameData = 2;
  public static final int GameDataType = 3;
  public static final int Meteo = 4;
  public static final int Mode = 5;
  public static final int SchoolDate = 6;
  public static final int bonusScore = 7;
  public static final int legNameType = 8;
  public static final int metersDistance = 9;
  public static final int metersWalked = 10;
  public static final int prizeWon = 11;
  public static final int virtualPriceType = 12;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xdc26d82528834e88L, 0x933cf0e9f65c69c4L);
    builder.put(0x5d61ef6eeb9ac5a5L, BonusPointType);
    builder.put(0x5d61ef6eeb9ac5a9L, ChallengeData);
    builder.put(0x5d61ef6eeb9ac548L, GameData);
    builder.put(0x23eac9cba8f42c9dL, GameDataType);
    builder.put(0x5d61ef6eeb9ac55aL, Meteo);
    builder.put(0x5d61ef6eeb9ac55eL, Mode);
    builder.put(0x5d61ef6eeb9ac5faL, SchoolDate);
    builder.put(0x5d61ef6eeb9ac5b0L, bonusScore);
    builder.put(0x5d61ef6eeb9ac5eaL, legNameType);
    builder.put(0x23eac9cba8deb2a6L, metersDistance);
    builder.put(0x5d61ef6eeb9ac577L, metersWalked);
    builder.put(0x5d61ef6eeb9ac593L, prizeWon);
    builder.put(0x5d61ef6eeb9ac59eL, virtualPriceType);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
