package GsML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_ChallengeInstance;
  private ConceptPresentation props_GameSimulation;
  private ConceptPresentation props_SingleGameExecution;
  private ConceptPresentation props_dataDrivenActionInstance;
  private ConceptPresentation props_eventDrivenActionInstance;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.ChallengeInstance:
        if (props_ChallengeInstance == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x26aa16acedaa4cf5L, 0xa912305a69f850f0L, 0x19b939282f67a0afL, 0x19b939282f67a0c6L, "challengeType", "", "");
          props_ChallengeInstance = cpb.create();
        }
        return props_ChallengeInstance;
      case LanguageConceptSwitch.GameSimulation:
        if (props_GameSimulation == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_GameSimulation = cpb.create();
        }
        return props_GameSimulation;
      case LanguageConceptSwitch.SingleGameExecution:
        if (props_SingleGameExecution == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("singleGameExecution");
          props_SingleGameExecution = cpb.create();
        }
        return props_SingleGameExecution;
      case LanguageConceptSwitch.dataDrivenActionInstance:
        if (props_dataDrivenActionInstance == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_dataDrivenActionInstance = cpb.create();
        }
        return props_dataDrivenActionInstance;
      case LanguageConceptSwitch.eventDrivenActionInstance:
        if (props_eventDrivenActionInstance == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_eventDrivenActionInstance = cpb.create();
        }
        return props_eventDrivenActionInstance;
    }
    return null;
  }
}
