package GsML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptGameSimulation = createDescriptorForGameSimulation();
  /*package*/ final ConceptDescriptor myConceptSingleGameExecution = createDescriptorForSingleGameExecution();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptGameSimulation, myConceptSingleGameExecution);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.GameSimulation:
        return myConceptGameSimulation;
      case LanguageConceptSwitch.SingleGameExecution:
        return myConceptSingleGameExecution;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList();
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForGameSimulation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GsML", "GameSimulation", 0xe0fa730698c04625L, 0xa0e1147e7b18cdbdL, 0x60c3ef30124ec194L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:a9609886-b83f-420c-94d6-601f7eba29df(GsML.structure)/6972679637844279700");
    b.version(2);
    b.associate("gameInstance", 0x60c3ef30124ecea4L).target(0x119e117f12604f12L, 0xb46eefd3d0e4c44fL, 0x19b939282ee57042L).optional(false).origin("6972679637844283044").done();
    b.aggregate("listOfExecutions", 0x60c3ef30124ecd3aL).target(0xe0fa730698c04625L, 0xa0e1147e7b18cdbdL, 0x60c3ef30124ec3b0L).optional(false).ordered(true).multiple(true).origin("6972679637844282682").done();
    b.alias("gameSimulation");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSingleGameExecution() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GsML", "SingleGameExecution", 0xe0fa730698c04625L, 0xa0e1147e7b18cdbdL, 0x60c3ef30124ec3b0L);
    b.class_(false, false, false);
    b.origin("r:a9609886-b83f-420c-94d6-601f7eba29df(GsML.structure)/6972679637844280240");
    b.version(2);
    b.associate("classroom", 0x60c3ef30124ec582L).target(0x119e117f12604f12L, 0xb46eefd3d0e4c44fL, 0x29c2332daad26af7L).optional(false).origin("6972679637844280706").done();
    b.associate("player", 0x60c3ef30124ec63eL).target(0x119e117f12604f12L, 0xb46eefd3d0e4c44fL, 0x548347b052b52548L).optional(true).origin("6972679637844280894").done();
    b.associate("dataActionInstance", 0x60c3ef30124ec800L).target(0x119e117f12604f12L, 0xb46eefd3d0e4c44fL, 0x687da624474faca0L).optional(true).origin("6972679637844281344").done();
    b.associate("eventActionInstance", 0x60c3ef30124ecc6cL).target(0x119e117f12604f12L, 0xb46eefd3d0e4c44fL, 0x687da624474faca3L).optional(true).origin("6972679637844282476").done();
    b.alias("singleGameExecution");
    return b.create();
  }
}
