package RetrieveInstances.plugin;

/*Generated by MPS */

import com.google.gson.JsonObject;

public class DailyPeriod {
  public JsonObject instances;


  public DailyPeriod(JsonObject instances) {
    this.instances = instances;
  }
}
