package RetrieveInstances.plugin;

/*Generated by MPS */


public class PointPeriodState {
  public DailyPeriod daily;
  public WeeklyPeriod weekly;


  public PointPeriodState(DailyPeriod daily, WeeklyPeriod weekly) {
    this.daily = daily;
    this.weekly = weekly;
  }


  public DailyPeriod getDaily() {
    return this.daily;
  }
  public WeeklyPeriod getWeekly() {
    return this.weekly;
  }
}
